/**
 * VideoScript Model
 * Stores video scripts generated by AI
 */

const mongoose = require('mongoose');

// Scene schema for individual scenes in a script
const SceneSchema = new mongoose.Schema({
    sceneNumber: {
        type: Number,
        required: true
    },
    location: {
        type: String,
        default: ''
    },
    shotType: {
        type: String,
        enum: ['goc_trung', 'can_canh', 'goc_rong', 'overlay'],
        default: 'goc_trung'
    },
    description: {
        type: String,
        required: true
    },
    voiceOver: {
        type: String,
        default: ''
    },
    source: {
        type: String,
        default: 'Quay mới'
    },
    note: {
        type: String,
        default: ''
    }
}, { _id: false });

// Main VideoScript schema
const VideoScriptSchema = new mongoose.Schema({
    // Owner - only this user can access
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true
    },
    
    // Basic info
    title: {
        type: String,
        required: true,
        trim: true
    },
    duration: {
        type: String,  // Free text, e.g. "3 phút", "5 phút"
        default: ''
    },
    requestedSceneCount: {
        type: Number,
        default: 6
    },
    size: {
        type: String,
        enum: ['vertical', 'horizontal', 'square', ''],
        default: ''
    },
    hasVoiceOver: {
        type: Boolean,
        default: true
    },
    
    // Content
    summary: {
        type: String,
        default: ''
    },
    scenes: [SceneSchema],
    
    // Metadata
    otherRequirements: {
        type: String,
        default: ''
    },
    ideaMode: {
        type: String,
        enum: ['manual', 'ai', 'concept_suggestion'],
        default: 'ai'
    },
    videoGoal: {
        type: String,
        default: ''
    },
    targetAudience: {
        type: String,
        default: ''
    },
    featuredProductService: {
        type: String,
        default: ''
    },
    selectedConceptTitle: {
        type: String,
        default: ''
    },
    
    // Status
    status: {
        type: String,
        enum: ['draft', 'completed'],
        default: 'draft'
    }
}, {
    timestamps: true
});

// Index for efficient querying by user
VideoScriptSchema.index({ userId: 1, createdAt: -1 });

// Virtual for scene count
VideoScriptSchema.virtual('sceneCount').get(function() {
    return this.scenes ? this.scenes.length : 0;
});

// Ensure virtuals are included in JSON
VideoScriptSchema.set('toJSON', { virtuals: true });
VideoScriptSchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('VideoScript', VideoScriptSchema);
